# Generated by Django 6.0.2 on 2026-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('ngo_id', models.IntegerField()),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('employee_id', 'ngo_id')},
            },
        ),
    ]
